// Code generated by protoc-gen-go-grpcserver. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpcserver v1.2.0
// - protoc             v3.12.4
// source: thumbnailproxy_grpc.proto

package thumbnailproxy_grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ThumbnailProxyClient is the client API for ThumbnailProxy service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ThumbnailProxyClient interface {
	GetThumbnail(ctx context.Context, in *URLRequest, opts ...grpc.CallOption) (*URLResponse, error)
}

type thumbnailProxyClient struct {
	cc grpc.ClientConnInterface
}

func NewThumbnailProxyClient(cc grpc.ClientConnInterface) ThumbnailProxyClient {
	return &thumbnailProxyClient{cc}
}

func (c *thumbnailProxyClient) GetThumbnail(ctx context.Context, in *URLRequest, opts ...grpc.CallOption) (*URLResponse, error) {
	out := new(URLResponse)
	err := c.cc.Invoke(ctx, "/thumbnailproxy_grpc.ThumbnailProxy/GetThumbnail", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ThumbnailProxyServer is the server API for ThumbnailProxy service.
// All implementations must embed UnimplementedThumbnailProxyServer
// for forward compatibility
type ThumbnailProxyServer interface {
	GetThumbnail(context.Context, *URLRequest) (*URLResponse, error)
	mustEmbedUnimplementedThumbnailProxyServer()
}

// UnimplementedThumbnailProxyServer must be embedded to have forward compatible implementations.
type UnimplementedThumbnailProxyServer struct {
}

func (UnimplementedThumbnailProxyServer) GetThumbnail(context.Context, *URLRequest) (*URLResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetThumbnail not implemented")
}
func (UnimplementedThumbnailProxyServer) mustEmbedUnimplementedThumbnailProxyServer() {}

// UnsafeThumbnailProxyServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ThumbnailProxyServer will
// result in compilation errors.
type UnsafeThumbnailProxyServer interface {
	mustEmbedUnimplementedThumbnailProxyServer()
}

func RegisterThumbnailProxyServer(s grpc.ServiceRegistrar, srv ThumbnailProxyServer) {
	s.RegisterService(&ThumbnailProxy_ServiceDesc, srv)
}

func _ThumbnailProxy_GetThumbnail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(URLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ThumbnailProxyServer).GetThumbnail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/thumbnailproxy_grpc.ThumbnailProxy/GetThumbnail",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ThumbnailProxyServer).GetThumbnail(ctx, req.(*URLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ThumbnailProxy_ServiceDesc is the grpc.ServiceDesc for ThumbnailProxy service.
// It's only intended for direct use with grpcserver.RegisterService,
// and not to be introspected or modified (even as a copy)
var ThumbnailProxy_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "thumbnailproxy_grpc.ThumbnailProxy",
	HandlerType: (*ThumbnailProxyServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetThumbnail",
			Handler:    _ThumbnailProxy_GetThumbnail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "thumbnailproxy_grpc.proto",
}
